### ISSUE TITLE
Copyright Licence

### ISSUE THREAD

**Issue by ldo** [yuki-koyama/blender-cli-rendering#36]
In your readme, you consider that this package is a “derivative work” of Blender, so therefore has to be subject to the same licence. Certainly the Blender Foundation also seems to think the same of users of its APIs, but I should point out that this goes against just about every discussion of the subject in other open-source projects.

For the best-known example, you may have heard of the _Oracle vs Google_ case. The US Supreme Court [verdict](https://www.zdnet.com/article/what-googles-api-copyright-win-over-oracle-means/) on that made it quite clear that Oracle [could not stop](https://techcrunch.com/2021/07/01/months-later-were-still-making-sense-of-the-supreme-courts-api-copyright-ruling/) Google from using the Java APIs (even if it actually dodged the question of copyrightability of APIs).

For another example, the Linux kernel docs [explicitly say](https://www.kernel.org/doc/html/latest/process/license-rules.html) that userland code can make use of APIs that interface to the kernel without implications for their licensing. (Kernel modules, on the other hand, are considered “derivative works”.)

The basic point is that compatibility with APIs is essential for providing basic purely technical functionality, and so cannot be restricted by copyright for that reason.

I’m not asking you to change the licensing of your project, merely pointing out that it is not as constrained--should not be as constrained!--as you might think.

**Comment by yuki-koyama** [comment]
Thank you very much for sharing the context! This was really, really helpful for me.

I think I should correct the README.md. It currently assumes "the use of GPL APIs automatically makes the code GPL since it is considered a derivative work", but now I realize this is not likely to be correct. I will not change the license itself (Ton wanted every Blender-related code to be free: [blog](https://code.blender.org/2019/06/blender-is-free-software/)), but I will surely fix the misleading sentence.
